### ISSUE TITLE
trailingSlash: "never" not working

### ISSUE THREAD

**Issue by johnnyreilly** [Azure/static-web-apps#1017]
**Describe the bug**

The `"trailingSlash": "never"` [aspect of `staticwebapp.config.json` says](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#never): 

> When setting trailingSlash to never, all requests ending in a trailing slash are redirected to a non-trailing slash URL. For example, /contact/ is redirected to /contact.

This doesn't appear to be the case, at least for my own site.  Consider:
1. https://blog.johnnyreilly.com/2021/07/07/output-connection-strings-and-keys-from-azure-bicep/
2. https://blog.johnnyreilly.com/2021/07/07/output-connection-strings-and-keys-from-azure-bicep

You would expect 1 to redirect to 2 - it does not.

**To Reproduce**

1. browse to https://blog.johnnyreilly.com/2021/07/07/output-connection-strings-and-keys-from-azure-bicep/
2. it does *not* redirect to https://blog.johnnyreilly.com/2021/07/07/output-connection-strings-and-keys-from-azure-bicep

See: 
- https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/baa16c3e95b1c8cb2980ff468f7b39f26c97a9ac/blog-website/staticwebapp.config.json#L2
- https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/main/.github/workflows/build-and-deploy-static-web-app.yml

This is all public.

**Expected behavior**
Redirection to occur as described. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1010525/208285064-5c00614e-3c63-4fdd-ac92-3782b379feb9.png)

**Device info (if applicable):**
N/A

**Additional context**

**Comment by vivekjilla** [comment]
@johnnyreilly thanks for providing all the details. 
This could be because of the location of staticwebapp.config.json file. It should be present inside the folder specifies in `app_location`. But I could see the app_location is `build` subfolder: https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/main/.github/workflows/build-and-deploy-static-web-app.yml#L116, where as the config.json is outside.

Details about the file location: https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#file-location

Can you please try moving it inside the build folder and see if it works. Thanks!

**Comment by johnnyreilly** [comment]
I will try! Thanks for noticing - I switched my build process to be outside for the task the other week - it's probably a remnant of that

**Comment by johnnyreilly** [comment]
you are correct! Fixed!
