### ISSUE TITLE
Deploying Next js hybrid app is failing on Azure SWA

### ISSUE THREAD

**Issue by appanasantosh** [Azure/static-web-apps#1054]
Trying to deploy Next js hybrid app on Azure SWA is throwing following error.

npm ERR! Missing script: "build"
npm ERR! 

---End of Oryx build logs---
Oryx build has completed. Took 6.0478771 seconds. Exit Code: 1
Oryx has failed to build the solution.

**Comment by vivekjilla** [comment]
Hi @appanasantosh Can you please check if you have package.json in your repo and it has `build` command in it.
Also, just FYI, SWA will take care of building the app, so you don't need to build it before hand.

Can you also please share your workflow file to get more context. TIA!

**Comment by appanasantosh** [comment]
Hi @vivekjilla I have an pipeline template, where I run build and zip the build output and drop it in artifacts. From there in the deploy step, I will unzip the folder and try to deploy the files from the build folder into azure SWA. 
As the Nextjs build output has package.json file Oryx is trying to build, which has been already built. So I have removed the package.json file from build folder, now it is skipping the build as it is already built. But now I am getting another error i.e unable to find the index "Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your deployment configuration file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.".

my inputs are:  app_location: "/build" # App source code path
                    # api_location: "" # Api source code path - optional
                    output_location: "" # Built app content directory - optional

**Comment by vivekjilla** [comment]
Hi @appanasantosh So with Next.js, there are two ways to host the site. 
- If you only need static contents and don't need server side capabilities, you can use `static html export` feature and there you can build it before hand and zip  the out folder and deploy it using the SWA workflow.
- But if you need server side rendering capabilities of Next.js, it's in public preview now and at this point we don't yet support `skip_app_build` (or building the app on your own). We need Oryx to build the app in order to deploy it correctly. Please see if you can use Oryx to build the app.
We're working on improving this experience and to support building the app separately. Sorry for the inconvenience.

You can find more details at  https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs

**Comment by appanasantosh** [comment]
Hi @vivekjilla, I am trying to deploy hybrid app. So I cannot use my template, and I should depend on the default pipeline?

**Comment by vivekjilla** [comment]
Yes, unfortunately, thats the only way today. Apologies for the inconvenience.

**Comment by appanasantosh** [comment]
I tried the default behavior with Oryx before. But there is another issue, i.e. the size limit of 100MB. Where as the cache folder itself crosses 100 MB size. So, is there any recommended approach to fix this?

**Comment by vivekjilla** [comment]
Hi @appanasantosh We're working on improving these limits. For now, you can use the api_build_command as a workaround to delete the cache folder and any other node_modules you don't need like this `api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'`

For more details: https://github.com/Azure/static-web-apps/issues/1034#issuecomment-1399256154

**Comment by Reshmi-Sriram** [comment]
Hey @appanasantosh ,
SWA now supports `standalone` feature of Next.js. This should help in the app size constraints. Do try it out and let us know if it works! For more details check out this [thread](https://github.com/Azure/static-web-apps/discussions/1066).

**Comment by appanasantosh** [comment]
Thanks @vivekjilla, now app has deployed successfully. But getting 502 error. Am I missing anything?

**Comment by vivekjilla** [comment]
@appanasantosh Glad the deployment succeeded. 502 could be due to missing configurations or dependencies. You can [enable application insights](https://learn.microsoft.com/en-us/azure/static-web-apps/monitor) to get more logs from the server and see what's missing. 

Here's an issue #1059 where the 502 was coming because a runtime dependency was part of devDependencies.

**Comment by appanasantosh** [comment]
Thanks @vivekjilla... Yes, issue was with dependencies referred in next.config. Now it is working fine, as I have moved dependencies from dev dependencies to dependencies.

**Comment by appanasantosh** [comment]
@vivekjilla Can we use staticwebappconfig.json with frontdoorid?

**Comment by vivekjilla** [comment]
Hi @appanasantosh sorry, staticwebapp.config.json is not yet supported with next.js. we're working on enabling it currently.

**Comment by dmarvar** [comment]
Hi @vivekjilla. Do we have any updates concernig the support of skip_app_build ? When using Oxyr build functionality it works well but I can not make work with my own artifact, there is any doc on that? 

Thanks a lot !
