### ISSUE TITLE
Pass Azure configuration settings to Next backend as environment variables. 

### ISSUE THREAD

**Issue by addexm** [Azure/static-web-apps#1114]
**Is your feature request related to a problem? Please describe.**
I may be mistaken, but currently, Azure Configuration settings (i.e.: those added via the portal) are not passed to the Next backend (for SSR use). This is a problem since it will effectively force secrets to be stored/managed in source control.

**Describe the solution you'd like**
Ideally, the Configuration settings set in Azure Portal would be passed to the Next backend as environment variables, similar to how Vercel manages secrets. It would be great if we could have environment slots for settings and use the new DB connections as well, but I won't push it. :)

**Describe alternatives you've considered**
Keeping secrets in next.config.js or piping them in during build are temporary alternatives, but both ultimately require secrets to be in source control and/or stored on disk next to the app. Another alternative would be running the Next backend using a managed identity which could pull secrets from Key Vault. I love this idea, actually, but I'm not sure it's possible. In any case, I'm very open to safe alternatives.

**Additional context**
I'm currently evaluating the preview support of Next  SSR on SWA for an app that we're beginning to design for release next year. If we could have some clarity around the roadmap of features (such as this one), it would go a long way towards providing reassurance that we're on the right track. Ultimately, I'd love to stay off Vercel and host Next on Azure (next to all of our other stuff) without the hassle of managing containers.

**Comment by vivekjilla** [comment]
Hi @addexm This should work today for Nextjs apps. If you set configuration settings in portal for SSR use, these should be accessible in your app as environment variables. 

Can you please share your app details like name and url, so that we can investigate this further. And also, the app setting name if it's okay to share. Apologies for the inconvenience!

Note: if you are using environment variables starting with `NEXT_PUBLIC_..` which are meant for client use, you would have to set them at build time like in github action where the build is happening for example.

**Comment by addexm** [comment]
@vivekjilla For a number of other issues (not related to SWA), we ended up moving to a classic App Service to host our Next app. Appreciate the response though!
