### ISSUE TITLE
Newly created GH Organisation not visible in Create Static Web App

### ISSUE THREAD

**Issue by victorp13** [Azure/static-web-apps#114]
I have existing Create Static Web App sites for which I integrated with GitHub some months ago. Today I noticed that after creating a new GitHub Organisation, the new org did not show up on the Create Static Web App page dropdown. 

I found that in order to be able to Grant access to this new Org, I need to:
- first revoke the existing rights for Azure Static Web Apps under my GH user Profile > Settings > Applications > Authorized OAuth Apps
- then reload the Create Static Web App page in the Azure Portal, and re-authenticate with GH. At which point, I can now Grant access to the new organisation.

This should be easily replicate if someone created a new organisation themselves. Basically, this means there currently is no way to Grant rights to new orgs without revoking/re-authing Static Web Apps to GH.

**Comment by ehamai** [comment]
Hi @victorp13 , you shouldn't have to revoke your original OAuth app.  Basically the issue is that authorizing our OAuth app is a point in time snapshot for the orgs that you currently have.  So if you add a new one, then you'll have to explicitly authorize that org for our app.

There's a section in this [doc ](https://docs.microsoft.com/en-us/azure/static-web-apps/getting-started?branch=pr-en-us-122734&tabs=angular#basics) which is linked from our UX and outlines what to do in this situation, but here's the part you're interested in:

**If you don't see any repositories, you may need to authorize Azure Static Web Apps in GitHub. Browse to your GitHub repository and go to Settings > Applications > Authorized OAuth Apps, select Azure Static Web Apps, and then select Grant. For organization repositories, you must be an owner of the organization to grant the permissions.**

We'll look into seeing if there's a better way for us to handle this but for now, this should get you unblocked.

**Comment by victorp13** [comment]
I see what you mean about having to authorize that org for the app. But, unless I'm mistaken (very much possible) the steps you describe in bold do not apply per org, but per account. So the new org will not actually inherit this authorization.

You can reproduce this in the way I described above. There is currently no way to authorize the app to a new org on an existing granted app. At least, that's my finding.

**Comment by victorp13** [comment]
Never mind, the way to do this is now clear to me. Turns out you can click "Azure Static Web Apps" in the list of Authorized OAuth apps, and get a new details page where you can Grant rights to individual Organizations. Thanks for clarifying this @ehamai!
