### ISSUE TITLE
"Functions" tab in portal unfinished?

### ISSUE THREAD

**Issue by dcollien** [Azure/static-web-apps#117]
Functions apps have:

- Code +  Test
- Integration
- Monitor
- Function Keys

as well as all the charts in the overview.

All this is missing from the "Functions" tab (clicking on each item does nothing).

**Comment by miwebst** [comment]
So Static Web Apps abstracts a lot of this away from customers to simplify the experience, that being said today you can still achieve a lot of these goals:

- Code + Test - you can't do this in Portal, but the functions VS code extension is great for this
- Monitor - you can add app insights by specifying the app insights api key
- Function keys - not really relevant since you can access it by going to your site

We are working to make this abstraction layer smoother and recognize that somethings are missing.

**Comment by dcollien** [comment]
Migrating a function app over to static web apps, some of the functions used function keys for doing admin tasks, this was the main one missing.

**Comment by miwebst** [comment]
For that scenario can you use the SWA roles to gate access to those functions to only those with an admin role?

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction.
