### ISSUE TITLE
Next.js middleware not running on 13.4.13

### ISSUE THREAD

**Issue by jessebs** [Azure/static-web-apps#1266]
**Describe the bug**

I have a working middleware.ts in Next.js that stopped working when I updated Next.js to 13.4.13.  I am deploying the app as a static web app.  Downgrading to 13.4.12 resolves the issue.

**Comment by sebastian-worcay** [comment]
I have the same issue here.

**Comment by atsd34** [comment]
I have same issue nexauth middleware doesn't work with 13.4.19 downgrading to 13.4.12 **didn't solve** the issue.

**Comment by nth-prime** [comment]
I still have this problem. I have a call with Azure support this evening.

Per the documentation at https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid I tried this on Next.js 12.3.2 to no avail.

**Comment by evenhagen** [comment]
> I still have this problem. I have a call with Azure support this evening.
> 
> Per the documentation at https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid I tried this on Next.js 12.3.2 to no avail.

Any updates after your call with Azure support?

**Comment by nth-prime** [comment]
I guess it should come as no surprise that support was not helpful. I have been trying to communicate with them for the last 36 hours.

The gist was that Next.js support for Azure Static Web Apps is in preview so they can't and won't assist in any way. Including suggesting another best practice for this type of deployment on Azure.

I'm working on retooling this for Vercel currently.

**Comment by rbourdon** [comment]
I have this issue as well, and downgrading to 13.4.12 resolved it for me.

**Comment by alexrabin** [comment]
Might be related to these
https://github.com/vercel/next.js/discussions/48441#discussioncomment-5834514
 https://github.com/vercel/next.js/discussions/46722

**Comment by rbourdon** [comment]
> Might be related to these [vercel/next.js#46722](https://github.com/vercel/next.js/discussions/46722) - it says Middleware is only available on the edge and not on node.js [vercel/next.js#48441 (comment)](https://github.com/vercel/next.js/discussions/48441#discussioncomment-5834514)

It's limited to the edge runtime API but will run in node. I'm using next-auth's middleware, no node APIs. It's working okay for me with 13.4.12 or earlier _except on cached SSG pages_

**Comment by sebastian-worcay** [comment]
Hi guys,
regarding middleare there was some discussion on AWS realted to it having the same issue:
https://github.com/aws-amplify/amplify-hosting/issues/3641

The root cause for middleare bek broken seems to be:
https://github.com/vercel/next.js/pull/52492

Would like to get an update on this from the Azure Statitc Web App Team as middleware is still broken on Azure unsing Next.js with version greater than 13.4.12.

**Comment by sebastian-worcay** [comment]
Rechecked on 13.5.4 and still an issue.

**Comment by rbourdon** [comment]
> TBH I dont think that the middleware feature fits into the "preview" category. You may use it to work entirely with SSG and i18n all together with App Router and a headless cms at build.
> 
> Also it is not stated that the middleware is not supported [here](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#unsupported-features-in-preview).

It's specifically mentioned as a supported feature [on this page](https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs?source=recommendations#hybrid-nextjs-applications-preview). I had some trouble even on 13.4.11/12 using SSG and next-auth :(

**Comment by sebastian-worcay** [comment]
Still an issue with latest next.js 13.5.6.

**Comment by daniel-soli** [comment]
any news on this issue?

**Comment by sebastian-worcay** [comment]
As next.js 14 is announced and this is still an issue on azure side I am really considering if we need to move our Next.js web application to some other hosting provider than azure. 😢
Saddens me because I am usually more than happy with Azure products.

**Comment by bertrand-riviere** [comment]
indeed, this is really a showstopper ☹.
since AWS has managed to fix the same issue (https://github.com/aws-amplify/amplify-hosting/issues/3641#issuecomment-1718059254), I don't understand why Azure team couldn't.

**Comment by lobatolais** [comment]
Any updates? 😔

**Comment by changeworld** [comment]
Same issue here :(
This is still an issue on azure side I am really considering if we need to move our Next.js web application to some other hosting provider than azure :(
Saddens me because I am usually more than happy with Azure products.

**Comment by rickliveshere** [comment]
Are there any updates or a roadmap for when this issue may be resolved by the team? 

I've seen in other threads that infrastructure changes may be required in Azure to more broadly support app based routing, indicating months, though it would be good to have an understanding of this so we can make a decision how to resolve. 

We've been holding off doing a NextJS upgrade due to the middleware issue in this ticket, however we may need to consider migrating to an alternative platform as a security vulnerability requires an upgrade (see https://github.com/advisories/GHSA-c59h-r6p8-q9wc). Please could anyone from the SWA team advise?

**Comment by thomasgauvin** [comment]
Next.js support is limited on Azure Static Web Apps for versions 13 and above, including the app router and React Server Components. App Service may be a more reliable host at this time for these versions, and we expect to iterate on our Next.js support on Static Web Apps in 2024.

**Comment by thomasgauvin** [comment]
Hi folks! This issue is now resolved with our improvements to Next.js support on Static Web Apps, with support for Next.js 13 & 14 and further features. I'll be closing this thread, please try out the newest improvements and let us know how it goes in the announcement thread: https://github.com/Azure/static-web-apps/discussions/1428
