### ISSUE TITLE
How to deploy without build

### ISSUE THREAD

**Issue by ridomin** [Azure/static-web-apps#127]
My web application does not require any `build` process, neither `node_modules` (note there is a package.json with dev dependencies).

How should I configure my GH workflow to avoid running any build at all? (files in my repo are the files I want to be served)

When I try to a get a PR validation, I got the error
```
The content server has rejected the request with: BadRequest
Reason: The number of files in the app content folder exceeds the limit of 4000.
```

what makes me thing `npm i` was executed.

**Comment by miwebst** [comment]
I assume your project does not normally have more than 4k files? npm install will happen automatically if a package.json is detected. Normally when someone does not have a build step they do not have a package.json, is there a reason you have that? 

We usually see someone having all of their static content in either the root or a specific folder (with no package.json in that folder as it would be published) and then specify the root or specific folder as the app_location.

**Comment by ridomin** [comment]
I'm using package.json to install development tools like a local web server, linters, etc.. Note all [my dependencies](https://github.com/ridomin/iothub-webclient/blob/master/package.json#L16) are `devDependencies`

One workaround I found (by accident), is to include a build step in my package.json producing an [error](https://github.com/ridomin/iothub-webclient/runs/963397540?check_suite_focus=true#step:4:69), but didnt fail the build and the output was available.

I can copy the required files to an _app_root_ folder, but it seems not very friendly.

Is there any option to avoid installing devDependencies? or exclude package.json at all?

I just want to publish the same files I have in my root folder. BTW, this is how I'm deploying `master` to GitHubPages.

**Comment by miwebst** [comment]
Ah this makes sense. Thanks for sharing the error log too, that was very helpful. So the main problem here is that we have an expectation that if we find a package.json then we will run the build or build:azure npm commands. The reason for this expectation is there were a number of customers who had issues because they built with some other command (i.e. docs:build) and thus we would not actually build their project causing silent errors. We made this error explicit but seems like for this case (package.json but no build) you explicitly do not want that behavior. We will think about this and get back to you. 

Also on you GithubPages, are you able to access the package.json?

**Comment by ridomin** [comment]
Even if you find a package.json you should not install devDependecies ever, you can do it with `npm install --only=prod`

and yes, here it is my p.json in my deployed GitHub pages site: https://mqtt.rido.dev/package.json (I didnt notice, but honestly I dont mind at all, it's also public on GitHub anyway).

My use case is to stress-out simplicity. 
What I commit is what is served without any build or intermediate step, this offers an awesome innerloop productivity with easy hot reload, and what is in production is exactly what I run locally.

Thanks to ES6 modules support in the browser, I dont need webpack, rollout or babel, to do modern JS and take advantage of TS-like features in VSCode.

Happy to discuss further if that helps

Rido

**Comment by ridomin** [comment]
Also, did you notice this build run succeed? https://github.com/ridomin/iothub-webclient/actions/runs/201200266 because the npm run script?

**Comment by miwebst** [comment]
So if you look at the logs for the successful case, we install the dev dependencies separately and these are not included in your final output. This is the reason your build (when you specify an npm run build) succeeds.

The overall problem you are running into is that if Oryx detects a package.json then we assume that you'd like us to build your content. As I described above, this was done because it was confusing for a lot of folks why we were not building their projects correctly if the build or build:azure scripts were missing. For your scenario, you don't want this to be the case (i.e. purely static content) but you want to continue having the package.json in the same folder as this static content.

We could make a feature to account for this case (purely static content + package.json) but I don't think this would be that common. Especially since the package.json ends up being included in the site content, I feel like this is probably not a best practice (even if its public on Github anyway). A better solution may be to have the package.json at the root of the project and then a folder called static or app that has all of your static content.

**Comment by ridomin** [comment]
ok, I agree that having the content and p.json in the same folder is not a best practice. I can move the content to a subfolder.

Which npm script should I ran in that case?

**Comment by miwebst** [comment]
So if you have all of your static content in a subfolder then you can just update your workflow file to have the app_location be the new subfolder. Then your site will be treated correctly as a truly static website and will deploy as such.
