### ISSUE TITLE
Bulk Add Users and Expand 25 User Limit?

### ISSUE THREAD

**Issue by theonewolf** [Azure/static-web-apps#134]
Background: we use Azure Static Web Apps for internal intranet documentation sites right now.

Thus, we are heavy users of **access control** and actually have none of our sites public.

We hit two problems with user management:

1. The 25 person limit is very stifling and means this product isn't actually usable for what we want it for right now.

2. There is no bulk import, or domain add say via Azure AD (ideally, we could let in any user on our domain).
    + We also need a method of easily granting access on our domain without manually sharing a URL / link.  If the product emailed the user that would be acceptable for now.

**Comment by miwebst** [comment]
Agreed the 25 person limit is too restrictive, this is something that we added for preview and will relax as we make our way towards GA.

Bulk import is an interesting idea, we will keep this in mind as we continue to iterate on this model!

**Comment by theonewolf** [comment]
@miwebst any documentation or update on when GA might be (or the marching closer)?

**Comment by theonewolf** [comment]
Or expanding the limit?

**Comment by takekazuomi** [comment]
any  update ?

**Comment by theonewolf** [comment]
We are migrating off the platform today, as we can no longer continue with a 25 person limit.

**Comment by takekazuomi** [comment]
me too

**Comment by anthonychu** [comment]
Sorry the feature is unable to support you right now. Can you please share what number would be suitable so we can work on something that works for your scenarios in the future?

@theonewolf For your intranet scenario, would you prefer a way to limit access to a VNET instead? Or would it be better to have the site public and providing a way to lock down the AAD integration to users your organization? Do you require additional customization (such as using roles from AAD or executing a function to perform a database look up on log in)?

**Comment by takekazuomi** [comment]
For us, 100 is enough.

**Comment by takekazuomi** [comment]
@theonewolf
We use a script (example) like the link to generate an invitation URL and distribute it on Slack. The URL itself is meaningful only to the person you are invited to, so it doesn't matter if it's visible to others.
There is a limit of 25 people, so it's not very useful. It is unfortunate.
https://gist.github.com/takekazuomi/408c5198d6dbd0cddfe3f1864379d201

**Comment by theonewolf** [comment]
@takekazuomi thank you for the insights and the script.  The script is very valuable.

@anthonychu we were operating with it as if it was another cloud resource like dev.azure.com.  We weren't requiring VPN to access it, which is refreshing and easier on our staff especially when not able to VPN.

For our current use case, **public + AAD SSO** limited to our organization / domain would be ideal.  We are OK granting access to everyone in our org.  One day, I'm sure it would be nice to map them to groups, but we don't need that right now.  No custom functions needed for us.

We would stay if that was possible.  This is almost the perfect product for us!

**Comment by tcc-sejohnson** [comment]
I heartily second this! @anthonychu, 100 users would totally take care of us for now -- but later on, it would be great to have support for unlimited users. My use case is very similar to theonewolf's. We're using SWA to hold information on BI products, and the 25 user limit makes this product more of a toy than something that would ever be useful in an enterprise scenario. It's a shame, too; the tight integration between my frontend (in TypeScript) and my backend (in C#) has made development a dream.

Even better, it would be awesome to be able to give access through AAD groups. i.e. give group@mydomain.com access to the site, and then anyone who logs into the site and is in that group receives the roles assigned to the group. 

Thanks for all your work on this product, and I can't wait for GA!

**Comment by tcc-sejohnson** [comment]
@anthonychu 

Quick update from our end: I had to transfer our site to Azure Web Apps/Azure Functions and manually integrate msal-js for authentication, mainly because of the 25-user limitation.

I could see SWA being the _primary_ provider for all of our in-house documentation/resources if the user limit was increased or removed, and especially if we could optionally restrict logins to a single tenant. 

To give you an idea of how promising this platform is for us, it took me ~30 minutes to set up our site on it (with auth!). It took me almost a week of pursuing the minutae of the MSAL documentation to work out all of the bugs in moving it over to the other platform.

The following features would make this the viable platform we really wish it was:

1. No limit (or a much higher limit) to user role assignments
2. Bulk add/remove of users along with an automated link distribution system (such as an email)
3. (Optionally) Group integrations -- it would be nice to assign users to groups and then assign groups to roles

If you guys implemented these features, you'd have us captured for life -- and I imagine others would say the same. 

Again, thanks for your work -- I'd love to be able to use this platform!

**Comment by anthonychu** [comment]
@tcc-sejohnson We're working on restricting login to a single AAD tenant. Also investigating more ways to customize auth.

**Comment by AverageCakeSlice** [comment]
Any updates on this? I would love to adopt SWA as the de-facto standard amongst my apps, but this is definitely a major issue that's holding us back.
Additionally, does the user limit only apply to users with custom roles? Can you go beyond 25 users if you don't also add custom roles?

**Comment by mrfoster** [comment]
Firstly, I think SWA is a great offering and will hopefully allow us to stick with Azure for all our hosting needs rather than using other competing services.

However, I also could do with some clarity on:

1) Why there is a 25 user limit at all
2) What the 25 user limit exactly means, i.e. is it just for adding/managing users within the Azure portal and roles?
3) What the upgrade path is if the limitation is reached. 
4) Will this limit be phased out?
4) Does using a custom OIDC provider avoid the limitation
5) Example auth scenarios and appropriate method.
e.g. 
   a) Manually invite up to 25 users - use built in method. 
   b) Require custom user registration open to public - bring in custom OIDC provider?
   c) Allow access to all internal Azure AD without registration.
   d) API needs access to auth token to communicate with other APIs - note that SWA interferes with authorization header even if not needed.

My scenarios so far:

The first SWA I built had an API which needed to make MS Graph calls on behalf all Azure AD users in a single tenant (of which there are 100s).  I tried the built in mechanism but couldn't figure out how to get the token to pass to MS Graph. I figured it was simpler log the user in via OIDC in the client and pass the token up in the header.  Which was fine after figuring out that SWA was interfering with my auth header and that I needed to rename it.  Fortunately the authorisation was covered by MS Graph and was relatively easy.

I'm currently developing a second app which is open to the public to register. We have proposed using Auth0 for this and I assumed this would be a case of plugging in a custom OIDC provider, but what about this 25 user limit? I will be manually implementing user registration so obviously don't want to register them in the portal. The roles will be stuck in as claims for the user so happy to check this in code rather than routing. I'm unsure whether to:
a) Continue with custom OIDC provider in SWA
b) Bypass any built in auth and do my own token validation in Azure functions
c) Revert to using AspNet Core and Azure Web Apps

**Comment by mrfoster** [comment]
Apologies for hijacking this issue with less specific questions. I think I have a better understanding having taken a second look.

Feature | Free plan | Standard plan
-- | -- | --
Authorization (with custom roles and routing rules) | Maximum of 25 end-users that may belong to custom roles | Maximum of 25 end-users that may belong to custom roles

In answer to my own questions:

2) The limit is specifically relevant to the routing rules and not a limit on numbers of users that can be authenticated.
3) Roles are available to the API and checks can be performed manually within the functions without limitation. 
5) Bringing your own OIDC provider would allow users to bypass the manual registration
6) Not relevant to this particular issue but having realised I can manually specify the scopes and can access the token means there is less likely scenarios that will require completely breaking out of the built in methods.  I really think claims should be made available but this is a separate issue.

**Comment by tcc-sejohnson** [comment]
@mrfoster 

I've found much the same. Unfortunately, I feel that they have to figure out a way to either 1) Expose all MSAL functionality through their own custom API or 2) At least expose the tokens to the app to make this truly viable. The 25-person role limit also makes this non-viable for all but the smallest internal sites. Without that limit, this would be an absolute beast for documentation sites/internal portals.

**Comment by chan-vince** [comment]
> Agreed the 25 person limit is too restrictive, this is something that we added for preview and will relax as we make our way towards GA.
> 
> Bulk import is an interesting idea, we will keep this in mind as we continue to iterate on this model!

Any update on this since we've been GA for quite a few months now?

**Comment by anthonychu** [comment]
We released the feature to programmatically assign roles with a function. This allows you flexibility in how you want to manage roles and you're not restricted in the number of users who can have custom roles.

See the [documentation](https://docs.microsoft.com/azure/static-web-apps/authentication-authorization?tabs=function#role-management) for more details. There's also a [tutorial](https://docs.microsoft.com/azure/static-web-apps/assign-roles-microsoft-graph) with a sample app.

**Comment by chan-vince** [comment]
Thanks for clarifying - I was under the impression that the 25 user limit also applied to the Azure Functions, as it currently states on [the quotas page](https://docs.microsoft.com/en-gb/azure/static-web-apps/quotas).

For what it's worth it would still be desirable to have AAD integration so that roles/groups can be mastered there. But I can understand that the feature design & segmentation is carefully planned too. 😅

**Comment by anthonychu** [comment]
Thanks for pointing that out. I’ll update that page!

**Comment by Reshmi-Sriram** [comment]
Closing the issue, feel free to re-open if necessary!
