### ISSUE TITLE
Is there any way to execute remote build on deployment from GitHub Action to Function App as backend API

### ISSUE THREAD

**Issue by horihiro** [Azure/static-web-apps#152]
Now I'm trying to use puppeteer on Function App as backend API.
But it might be difficult that the size of deployment package is less than 30mb ([current limitation for API package](https://github.com/Azure/static-web-apps/issues/150#issuecomment-691599056)) because chromium binary in puppeteer is huge.

If remote build such as `--build remote` option of `func azure functionapp publish` can be used on deploytment, the limitation can be avoided.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=linux%2Ccsharp%2Cbash#project-file-deployment
![image](https://user-images.githubusercontent.com/4566555/93014523-b40c1880-f5ec-11ea-90fb-81e25a7e8ca6.png)

Could you please consider this option?

Thanks,

**Comment by miwebst** [comment]
This most likely will not be a supported option. The GitHub action is currently the only way to do build and deployment. This limit is put here in part so we can measure the needs of the community, so this is a great data point for us. I will followup if there are any changes to the limit soon but otherwise I believe your scenario will be blocked.

**Comment by horihiro** [comment]
Thanks @miwebst 

I don't know about the GitHub action in details, so my opinion might not be realistic.It looks that the action is processed by using docker container based on `mcr.microsoft.com/appsvc/staticappsclient:stable`.
Do we have any way to execute functions core tools with the above option `--build remote` inside the contaier?

**Comment by miwebst** [comment]
The remote build and the Static Web Apps container utilize the same technology to build the Azure Function, the build process is not the problem :) We have a limit in place because we own the underlying Azure Function that you are deploying your content to, this is done to provide a seamless experience (no need to worry about the underlying resources just write code). As I said above, this is mainly due to preview and these limits will change.

cc @anthonychu in case he wants to add anything

**Comment by horihiro** [comment]
Will this limitation be removed or become same as normal Azure Functions in GA?

**Comment by horihiro** [comment]
Currently, BYOF can be used in GA, so is it the best practice to use BYOF if the API package size is over 100MB?
ref: https://github.com/Azure/static-web-apps/issues/247#issuecomment-830715628

**Comment by miwebst** [comment]
Yes you can certainly use that to get around the limit :)
