### ISSUE TITLE
All .auth access returns index.html

### ISSUE THREAD

**Issue by rhalaly** [Azure/static-web-apps#181]
I have React app with this routes.json file (inside the public folder):
```
{
  "routes": [
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    },
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}
```

But all the login requests to, for example, `/.auth/login/google` or `/.auth/login/aad`, etc. just bring the `index.html` file, and my client routing tries to process it.

Any idea what can be the issue? (The project created with Create React App CLI)

**Comment by miwebst** [comment]
So those routes are matching the /* path and thus returning index.html. To avoid this (and this is something we are going to suggest for fallback routes going forward) you can use platform error overrides so that instead of returning a 404, it will return index.html. You can replace your fallback route with:

"platformErrorOverrides": [
    {
      "errorType": "NotFound",
       "statusCode": "200",
      "serve": "/index.html"
    }
  ]

https://docs.microsoft.com/en-us/azure/static-web-apps/routes#custom-error-pages

**Comment by rhalaly** [comment]
Thanks! I think that you should warn in your docs also about service workers. Because they can "override" the routes config.

**Comment by miwebst** [comment]
This is a great callout as we've seen this before. cc @craigshoemaker
