### ISSUE TITLE
CNAMERecord is invalid when CNAME record is correctly added in Azure DNS

### ISSUE THREAD

**Issue by therealburningman** [Azure/static-web-apps#202]
Hi! I love the idea Azure Static WebApps can have Static Site Generator build production releases.

I am stuck in a situation though where I use Azure DNS to manage a domain and have correctly set the CNAME record pointing to: `blue-coast-056e4a103.azurestaticapps.net`

This is the error I get in the **Azure Portal** when adding a domain that's correctly added:
`CNAMERecord is invalid. Please ensure the CNAME record has been created.`

When I do an nslookup I get this response:
`yoursite.mydomain.com	canonical name = blue-coast-056e4a103.azurestaticapps.net.
blue-coast-056e4a103.azurestaticapps.net	canonical name = azurestaticapps.trafficmanager.net.
azurestaticapps.trafficmanager.net	canonical name = msha-am2-0.staticsites-prod-westeurope.p.azurewebsites.net.
msha-am2-0.staticsites-prod-westeurope.p.azurewebsites.net	canonical name = waws-prod-am2-0ab44d07.sip.p.azurewebsites.windows.net.
waws-prod-am2-0ab44d07.sip.p.azurewebsites.windows.net	canonical name = waws-prod-am2-0ab44d07.cloudapp.net.
Name:	waws-prod-am2-0ab44d07.cloudapp.net
Address: 40.118.40.109
`

When I try to set the same thing in **Azure CLI** I get no result at all. And the custom domain isn't added straight away in the Azure Portal. After a minute it's populated and everything seems fine.
`az staticwebapp hostname set --hostname yoursite.mydomain.com --name yoursite`

Other information. The domain being managed has a TLD called '.one'.

**Comment by roguelj** [comment]
I am also running into this issue. Unfortunately however, using the CLI does not work. I can see a little bit more information by using the --debug flag. In this case, the 'CNAMERecord is invalid' error is also visible in the response.

**Comment by therealburningman** [comment]
> I am also running into this issue. Unfortunately however, using the CLI does not work. I can see a little bit more information by using the --debug flag. In this case, the 'CNAMERecord is invalid' error is also visible in the response.

might need some time to propagate?

**Comment by roguelj** [comment]
Entirely possible. To be honest, I haven't waited for the full '48 hours to propogate'.

DNS is frustrating!

**Comment by therealburningman** [comment]
When you're in a hurry. for sure. Hope it works out.

**Comment by anthonychu** [comment]
@therealburningman @roguelj Was it propagation or is it still a problem?

**Comment by roguelj** [comment]
I managed to get the www version of the domain name entered (eventually), and this worked. However the domain name without the www subdomain would refuse to be entered - same error message. As you can only enter one custom dns anyway (and I wanted both www and non-www to work), I have abandoned this little project completely.

**Comment by BipulRaman** [comment]
There is no provision for non-www subdomain. The whole functionality seems to be incomplete / broken.

**Comment by Brouilles** [comment]
Same here... No news about it?

**Comment by stemixreal** [comment]
Hi @BipulRaman there's no support yet for Apex domains but you can add any subdomain you choose. Ignore the www in the portal, it should say "e.g. www"

**Comment by miwebst** [comment]
Both are supported now, https://docs.microsoft.com/en-us/azure/static-web-apps/custom-domain?tabs=azure-dns

**Comment by bt-catena** [comment]
Also affected.
This happened on our SWA hosting our website.
It is not possible to add custom domains (both sub and apexdomains), neither through txt or cname records.
In the case of CNAMEs i get the "CNAME Recode is invalid" error, while the TXT records are never validated.
I made sure the DNS records are correct and can be resolved from 3rd party machines.
The CNAMEs also must be correct, since i did exactly the same record which which it worked previously (same dns zone in azure, same SWA).

**Comment by joslinmicrosoft** [comment]
@bt-catena So we believe the problem is caused by the presence of CAA records in your custom domain's _parent_ domain, which prevents the SWA platform from provisioning a certificate. For example, if you are trying to add yoursite.mydomain.com to the SWA and you have incompatible CAA records at mydomain.com (the parent domain), we will be unable to issue a certificate and the overall custom domain add process will fail.

You can either
1. remove these CAA records, or
2. add a new CAA record to enable our certificate provider, DigiCert, to issue certificates for your domain. this would be of the form `mydomain.com CAA 0 issue "digicert.com"`

After the record changes propagate, you should be able to try again.

**Comment by bt-catena** [comment]
Yes, just tried it first thing in the morning and worked. Thanks a lot!
Also makes total sense that you cannot issue any certs in that case.
Can we add this to the Custom Domain Documentation of SWA and show a different Error Message ?
I think the CNAME is invalid error message is rather confusing in that case. At least something along the lines of "Failed at provisioning certificate." would be good. The best would be of course to flat out tell the user that the CAA record is preventing them from adding a custom domain.

**Comment by miwebst** [comment]
Totally agree :) we are working on putting this in the UX.

**Comment by joslinmicrosoft** [comment]
As an update, we've updated the UX in the Azure portal to more clearly communicate certificate creation failures (on both initial create and subsequent renewals). Issues related to the CAA records will have additional details about allowing digicert.com to issue the certificate. Thank you for the feedback!

**Comment by sandeep-eroad** [comment]
Still not working! The documentation is incorrect. I have wasted a day going round in circles and it's annoying. Can someone please fix this properly?

**Comment by 8bg** [comment]
Same problem here. Posted a MS Question and received a suggestion to add a CAA record, however still doesn't add. See https://learn.microsoft.com/en-us/answers/questions/1160037/error-adding-www-subdomain-to-static-web-app?source=docs 

Is there anything else that can be done?

**Comment by Tailslide** [comment]
Also just had this error.. eventually the name shows up associated with the site even after the error.
Adding the CAA record didn't immediately help.

**Comment by SBFrancies** [comment]
I am still experiencing this error having added the CAA record.

**Comment by 8bg** [comment]
In my case this was eventually resolved by manually removing all CNAME and A records with the domain registrar. Specifically with Amazon (AWS Route 53), and then trying again.

**Comment by SBFrancies** [comment]
In my case I hadn't switched from the GoDaddy nameservers to the Azure ones in the GoDaddy DNS manager. The step is explained here: https://learn.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns#delegate-the-domain
but not in other guides.

**Comment by JOSE-DEUS** [comment]
I´m still  experiencing this issue having added the CAA record . In CLI I´m getting `Operation returned an invalid status 'Not Found'` error. Is there any other way to try to fix this issue?

**Comment by timgehr** [comment]
Having the same issue. I'm getting that Azure 404 page (attached), which I assume means that the CNAME is correct on Cloudflare's side and points to azure, but Azure won't let me add the CNAME saying "CNAME Record is invalid.  Please ensure the CNAME record has been created."

This is confusing to me, because clearly the CNAME does exist and point to azure but azure isn't recognizing it

![image](https://github.com/Azure/static-web-apps/assets/36209570/12df6c62-8157-4063-8eaa-a7e8d1be29cf)

**Comment by edgariscoding** [comment]
Same issue here

**Comment by DerStimmler** [comment]
@timgehr
To get it working with Cloudflare, I had to temporarily disable the proxy, add the domain to my Static Web App, and then re-enable the proxy afterwards.

**Comment by Panda-Sharp** [comment]
same issue here
