### ISSUE TITLE
Blazor .dll not found after publish

### ISSUE THREAD

**Issue by andreatosato** [Azure/static-web-apps#220]
Hi,
I'm developing Azure Static WebApps with Blazor (.net 5) and Functions (.NET 3.1).
This is this [repo](https://github.com/andreatosato/AzureWebSitesStatic)

After "build and deploy" Github Actions don't deploy .DLL files.
For example, for this library: Microsoft.AspNetCore.Components.dll
When I build solution on my machine there are many file:

- Microsoft.AspNetCore.Components.dll.br
- Microsoft.AspNetCore.Components.dll.gz

How can I deploy the app correctly?
Thanks a lot

**Comment by andreatosato** [comment]
I fix GitHub actions.
I publish separately api and app application.
Azure Functions must be compiled with .NET Core 3.1 and Blazor with .NET 5
[My result](https://github.com/andreatosato/AzureWebSitesStatic/blob/main/.github/workflows/azure-static-web-apps-orange-mushroom-011535a03.yml).
Now I need to set CORS on Azure Static Webapps

**Comment by anthonychu** [comment]
Looks like CORS is not the problem as the call is to the same domain as the Blazor app. The problem is the function app is failing to start.

https://orange-mushroom-011535a03.azurestaticapps.net/api/leagues

Currently, the only way to diagnose this problem is by adding Application Insights:

1. Go to the [Azure Portal](https://portal.azure.com/?feature.customportal=false#create/Microsoft.AppInsights) and create an Application Insights resource in the same region as your Static Web App.
1. After its Applications Insights resource is created, open it in the Azure portal.
1. Locate the Instrumentation Key and copy it.
1. Go to the Static Web App and add an app setting named `APPINSIGHTS_INSTRUMENTATIONKEY` and set its value to the key you copied.

In the Application Insights resource, open the Live Metrics page. You should see some logs appear when the function app tries to start.

**Comment by andreatosato** [comment]
Live metrics page is not working "Not available: your app is offline or using an older SDK".
I follow instruction step by step:
![image](https://user-images.githubusercontent.com/24985956/100195793-273cdf80-2ef8-11eb-99a4-5963e400265f.png)
Region is booth west europe.
I can't see log or live metric working. No request arrive to Application Insight.

**Comment by andreatosato** [comment]
My functions is in .NET Core 3.1, so I need to install this package: Microsoft.Azure.WebJobs.Logging.ApplicationInsights.
After that application insight start to log error.

I think that this is error: 
**Did not find functions with language [node].**


During GitHub Actions i find this log:

```
App Directory Location: 'blazor/wwwroot' was found.
Api Directory Location: 'func' was found.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1

Build Operation ID: |E4ijF8ERcBA=.c35455b2_
Repository Commit : f72f1f3190c2825fdf81063bb2ee93dbba63d676

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
Starting to build function app with Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1

Build Operation ID: |Wsf7Cr8yq3o=.a8fa038c_
Repository Commit : f72f1f3190c2825fdf81063bb2ee93dbba63d676

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
```

**Comment by anthonychu** [comment]
OK I see. I wonder if this is because you built your function app in a separate action. Because you're passing the build output of the function app to the Static Web Apps action, it's probably not able to determine that it's a .NET app, and it assumed it was Node.

To fix this, changing the `api_location` of your workflow file to `"Api"`. This should cause the action to build it and it should know it's a .NET function app because there's a csproj file.

@miwebst Not sure what we can do here.

@andreatosato Looks like you never saw any live metrics because the function app was not able to start at all. Can you check your App Insights traces to see if there are any logs?

**Comment by andreatosato** [comment]
@anthonychu great, works!

I'm waiting Azure Function in .NET 5 for fix GitHub Action but now workaround do great job!
Thanks a lot ❤️
