### ISSUE TITLE
trying to work with protected apis (functions)

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#243]
```
if (req.Headers.TryGetValue("x-ms-client-principal", out var header))
        {
            var data = header[0];
            var decoded = Convert.FromBase64String(data);
            var json = Encoding.ASCII.GetString(decoded);
            principal = JsonSerializer.Deserialize<ClientPrincipal>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
```

I tried to follow the example of the documentation, but it is not working.

1- this head is not being passed to the function (or I don't know what configuration is missing for this to occur)

2- forcing this head through the postman, an error occurs when trying to convert the json, because the result of it does not go as expected.

![image](https://user-images.githubusercontent.com/12803050/102785565-f88e1980-437c-11eb-8c0b-382eae77bb94.png)

I also tried the strategy of passing the 'ClaimsPrincipal', via injection, but it does not recover the logged user's session.

**Comment by mkarmark** [comment]
Hi @drma-dev, the x-ms-client-principal header should be passed to the function if the user is logged in. Are you still seeing the absence of the header even after successfully logging in?

**Comment by drma-dev** [comment]
This Header is not being passed, it passes in another called 'Token'.

And as I said, even if I force it to be passed, this error occurs that I showed.

**Comment by mkarmark** [comment]
So the value you passed in should never hit the function since we intentionally don't pass it on to the function to prevent spoofing attacks. Our x-ms-client-principal value if set is the only such header that'll reach the function but will only reach the function in the case of a logged in user. Do you mind giving us some app details (default hostname/app name) so that we can investigate things on our end?

**Comment by drma-dev** [comment]
https://github.com/drma-dev/VerusDate/tree/develop/src/VerusDate.Web

**Comment by anthonychu** [comment]
The header is not available locally. We are working on a local emulator that will allow you to simulate auth. Until then, you’ll likely want to have a separate code path while running locally to use a fake user.

The ClaimsPrincipal binding is currently not compatible with Static Web Apps auth, this will likely be fixed in the coming months.

The header should be passed correctly when deployed to Static Web Apps and the client is logged in. @mkarmark does the function need to be protected to receive the header? The current [routes.json](https://github.com/drma-dev/VerusDate/blob/develop/src/VerusDate.Web/wwwroot/routes.json) doesn’t have any routes that require authenticated users.

**Comment by drma-dev** [comment]
I was not testing on localhost. I can't even log in.

**Comment by drma-dev** [comment]
The authentication control I'm doing in the blazor itself, so I didn't define any of that in the routes.

The problem is with the APIs. Do I have to define API authentication control on the routes?

**Comment by drma-dev** [comment]
The only information passed in the header is this one, which I believe is because of the component I am using.
![image](https://user-images.githubusercontent.com/12803050/102992473-06b57480-44fa-11eb-9dcd-ae9d00a76cfb.png)

**Comment by anthonychu** [comment]
You can’t see the header in the browser network trace. We have a proxy that validates that cookie and injects a header from the cookie’s contents into the request that is received by the function app. You can only see the `x-ms-client-principal` in the function app. Can your function access the header?

**Comment by drma-dev** [comment]
@anthonychu 

```
var principal = StaticWebAppsAuth.Parse(req);
return new OkObjectResult("id=" + principal.Claims.FirstOrDefault(w => w.Type == ClaimTypes.NameIdentifier)?.Value);
```

![image](https://user-images.githubusercontent.com/12803050/103285670-8f7e5580-49bd-11eb-98f5-7b68d6feb621.png)

**Comment by anthonychu** [comment]
Do you have the cookie included in the Postman request?

**Comment by drma-dev** [comment]
I had tested from the wrong place. I made the call from within the site.

![image](https://user-images.githubusercontent.com/12803050/103306534-8d7fbb00-49ec-11eb-81bc-b7e1b96947f1.png)

**Comment by drma-dev** [comment]
I had tested from the wrong place. I made the call from within the site.

![image](https://user-images.githubusercontent.com/12803050/103308932-6fb55480-49f2-11eb-876a-dfa49b4fecf4.png)

**Comment by drma-dev** [comment]
I tried to recover the token, to work locally, but without success.

```
if (req.Headers.TryGetValue("x-ms-client-principal", out var header))
  {
      var data = header[0];
      return new OkObjectResult(data);
  }
  else
  {
      return new OkObjectResult("nothing");
  }
```
```
var token = await Http.Profile_GetView("123");
        Console.WriteLine("token:" + token);
```

![image](https://user-images.githubusercontent.com/12803050/103445073-7d671600-4c4e-11eb-936a-4e0d3c25429b.png)

**Comment by drma-dev** [comment]
It's magically working now. :)

**Comment by AverageCakeSlice** [comment]
@drma-dev do you happen to know why it's working for you now? I'm running into issues where I can get the header just fine when testing locally with the SWA CLI, but whenever I deploy it suddenly stops working, throwing a "Object reference not set to an instance of object" error when I try using the suggested code in: https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=csharp

**Comment by drma-dev** [comment]
it's been a while. I don't even know if this emulator already exists to run local. uses the same component I'm using, this should help.

**Comment by AverageCakeSlice** [comment]
Actually, I found the solution. I'm using a custom auth provider (Auth0), and the claims that get returned from the deployed object are different than the local version. Auth0's name claim type only returns the full name for some reason, so I had to make this modification to the code in the example I linked above:
From:
```csharp
identity.AddClaim(new Claim(ClaimTypes.Name, principal.UserDetails));
```
To:
```csharp
identity.AddClaim(new Claim(ClaimTypes.Name, principal.UserId));
```
This lets me retrieve the Auth0Id (e.g. `auth0|xxxxxxxxxxxxxxxxxxx`) instead of the default item in the user details property, which is just the first and last name of the user (e.g. `Mark Zuckerberg`)

**Comment by StiviiK** [comment]
Hi, we are experiencing a very similar issue. We have deployed a Azure Static Web App and a BYO Azure Function.   
@anthonychu I hope it is okay to hijack this "older" issue.

The `x-ms-client-principal` is never available if we call the API through our static web app `SWAURL.azurestaticapps.net/api/...`.    

For the authorisation we configured Azure Active Directory Version 2 (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#azure-active-directory-version-2). The User is authenticated and the auth cookie will be correctly send to the SWA as we can see in the request inspector from the browser.
![image](https://user-images.githubusercontent.com/8115642/157068441-ea1b392f-0761-4d1a-ba95-af147fb7e7bd.png)
(Please ignore the repsonse code of 403, this comes from our api as the client principal header is missing.
