### ISSUE TITLE
Error constructing handler for request of type MediatR.IRequestHandler`2[...]. Register your handlers with the container. See the samples in GitHub for examples.

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#245]
I have the following class definitions:
```
[assembly: FunctionsStartup(typeof(VerusDate.Api.Startup))]
namespace VerusDate.Api
{
    internal class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddCosmosRepository();

            builder.Services.AddHandles();
            builder.Services.AddPipelines();
            builder.Services.AddValidations();
        }
    }
}
```
```
public static void AddHandles(this IServiceCollection services)
{
    services.AddMediatR(Assembly.GetExecutingAssembly()); //needs only one class
}

public static void AddPipelines(this IServiceCollection services)
{
    services.AddTransient(typeof(IPipelineBehavior<,>), typeof(PerformanceBehaviour<,>));
    //services.AddTransient(typeof(IPipelineBehavior<,>), typeof(UserSessionBehavior<,>));
    services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
}

public static void AddValidations(this IServiceCollection services)
{
    services.AddSingleton<IValidator<ProfileAddCommand>, ProfileAddCommandValidation>();
}
```

It works normally on localhost, but it gives error when I go up to azure. I believe that my startup class is not being called.

**Comment by anthonychu** [comment]
Can you try to deploy the API to a regular Azure Function app? Hoping to isolate this problem and it would be great to know whether the error only happens in Static Web Apps.

**Comment by drma-dev** [comment]
It was missing to configure the settings.

But this error was strange, it is not related to this problem.

**Comment by joaocolombo** [comment]
Same problem, the message was not related with the problem... some hours in tests and research lost

**Comment by AsIndeed** [comment]
Same problem, wish you explained how to solve it

**Comment by drma-dev** [comment]
> It was missing to configure the settings.
> 
> But this error was strange, it is not related to this problem.

As I said, my specific problem was that my server was missing configuration.

**Comment by cmuebro** [comment]
Hello, 
we had exactly the same issue. In our case, the cause was that we created a new Cosmos DB container via Terraform. However, we forgot (via Terraform, Powershell, Portal or similar) to set the environment variables for AccountEndpoint, ContainerName, DatabaseName, DefaultDatabaseRUs etc. on the web app (Home > All resources > [your web app] > Settings > Configuration). 

Long story:
As a result of this the MediatR trying to execute the Command/CommandHandler. When instantiating the CommandHandler, the dependency injection tried to resolve the Repository for the newly created container, which led to an error because although we had set the connection settings in the local appsettings.json, but these environment variables did not yet exist in Azure. This meant that no connection to the container could be established via the repository, which is why resolving the DI failed, which is why the MediatR issued the corresponding error message that the CommandHandler could not be created (which is not a problem obviously the error message suggests). You maybe chould see the problem at the health state of the container.

Short story:
Check whether you have made settings, e.g. in your appsetting.json, which you have not yet stored as environment variables in your web app. It is most likely a setting that has to do in one way or another with an object that you want to have given to you in the constructor of your CommandHandler via DI.
