### ISSUE TITLE
Blazor PWA fails to load service worker

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#259]
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://green-grass-0dbf41210.azurestaticapps.net/routes.json' with computed SHA-256 integrity 'yBVJpqoaRNGFj+qrnQEGCVBli5KeOcJXudKFTddrE4c='. The resource has been blocked.`

I knew that this was a problem with github, as it changes the file before publication, but I configured what would be necessary and had no effect.

In the '.gitattributes' file add the content: * binary

Would there be anything else to do?

**Comment by anthonychu** [comment]
OK. I think this is a problem with Blazor PWA and related to #258. 

If you take a look at the service workers tab, you'll notice this error:
![image](https://user-images.githubusercontent.com/3982077/103800818-b6620a80-5001-11eb-9623-2cfa46d05a64.png)

Clicking on the error, you'll open the service worker script. Unfortunately, there's not a lot of information to diagnose this.

To resolve this, you need to change line 12 from:

```js
const offlineAssetsExclude = [ /^service-worker\.js$/ ];
```

to:

```js
const offlineAssetsExclude = [/^service-worker\.js$/, /^routes\.json$/];
```

To update that line, you have to update this file in your Blazor source:

https://github.com/drma-dev/VerusDate/blob/49737b263ca8fdc88af4c7423094273bc048e9d6/src/Client/wwwroot/service-worker.published.js#L12

## Explanation

During build, Blazor PWA generates a manifest containing all static assets in the app so that they can be cached for offline use. This file is generated at `/service-worker-assets.js`.

When a browser loads the PWA, it runs `/service-worker.js` (this is generated from `wwwroot/service-worker.published.js` in your Blazor app). This script creates the service worker and loads the assets listed in the assets file.

The problem occurs because `routes.json` was found and added to `/service-worker-assets.js` and the app attempts to load it. In production, we block access to `routes.json` for security reasons. This causes the service worker to fail to load. Adding routes.json to `offlineAssetsExclude` in the service worker script will skip the file and avoid the problem.

**Comment by anthonychu** [comment]
Updated title for other folks to find. Thanks @pierceboggan for the solution.

**Comment by drma-dev** [comment]
that works. thanks
