### ISSUE TITLE
How do we use for jekyll?

### ISSUE THREAD

**Issue by kheiakiyama** [Azure/static-web-apps#27]
This question is about `Azure/static-web-apps-deploy@v0.0.1-preview`.

My code is [here](https://github.com/kheiakiyama/trans-feed/tree/8e5088b00e01ce5b02ae3316448d04d277c91b41).

I defined `app_artifact_location` same as jekyll output directory like below.  

https://github.com/kheiakiyama/trans-feed/blob/8e5088b00e01ce5b02ae3316448d04d277c91b41/.github/workflows/azure-static-web-apps-blue-meadow-0f4ae8c00.yml

But this action did not work I expected. 
It looks that find out `index.html` from `app_location`  before find out contents from `app_artifact_location`.  

Below is build log.  
https://github.com/kheiakiyama/trans-feed/runs/703356187?check_suite_focus=true

No API app is not expected for Static Web Apps?

**Comment by miwebst** [comment]
Hi @kheiakiyama,

Can you try modifying your workflow like `app_artificat_location: ''` and `app_location: '_site'`?

Right now you are building your application before getting to the build and deploy action. When the build and deploy action runs, it will look for the `app_location` and try to build the source code there. Because Oryx does not support Ruby, it fails to detect the language and we assume that the content in that folder is purely static. Since your app location has an `index.html` file, we believe this is static content and we publish that folder.

Adjusting your workflow as I recommended above will provide the build and deploy action with only your built assets. Oryx should fail to determine the language (since it is purely static content at this point), we should find the `index.html` file as expected and then we will publish that folder.

**Comment by kheiakiyama** [comment]
@miwebst Thank you for your answer.
It worked!

I had confused because this document uses `app_artificat_location`.
https://docs.microsoft.com/en-us/azure/static-web-apps/publish-hugo

`hugo` does not have `index.html` under `app_location: ''`, so it works I understood.
