### ISSUE TITLE
Easier debugging for Functions of Static Web Apps

### ISSUE THREAD

**Issue by komayama** [Azure/static-web-apps#270]
Default deployed the Functions in Static Web Apps, there is no debugging feature. So we need to create the Application Insights and connection with the Functions in the following steps.

**Check logs with Application Insights**

1. In the Azure portal, create Application Insights.
2. Copy the Application Insights instrumentation key.
3. Add and save the instrumentation key to the application settings name APPINSIGHTS_INSTRUMENTATIONKEY in the Static Web Apps screen, configuration.
4. On the Application Insights screen, check the logs from Search.

When creating the Functions in Static Web Apps, We hope this site has a default feature with Application Insights like create Azure Functions App. Because now deployed functions can't debugging on Azure Portal.

**Comment by anthonychu** [comment]
We are working on the ability to add App Insights to your Static Web Apps functions from the portal. Hope to have this available in a month or two. Until then, the steps you’ve described to debug are correct.

**Comment by komayama** [comment]
@anthonychu 
I got it. Thank you for telling me.

**Comment by smakinson** [comment]
@anthonychu Is this still the recommended way? Support has said its not available for static web apps, but this shows it is:
https://docs.microsoft.com/en-us/azure/static-web-apps/monitor

I have a nodejs api, but the "yes" us disabled and I see: "App Insights is not supported for the current combination of subscription and location."

Could it be because I need to a manual step first?

Not related to this issue, but I've also been trying to verify if proxies.json should work with managed functions in static web apps, at the moment I have some working locally but see 404 when pushed to staging.
