### ISSUE TITLE
Custom build scripts - Action to upload only?

### ISSUE THREAD

**Issue by ItalyPaleAle** [Azure/static-web-apps#28]
I wanted to try this with [my blog](https://github.com/ItalyPaleAle/WithBlueInk) as a first attempt. However, the codebase requires some non-standard build steps, and this doesn't work with Oryx. In fact, I have custom build scripts and even a Makefile.

How can I write my own CI/CD definitions and just upload the pre-built assets to Azure SWA?

**Comment by aaronpowell** [comment]
Since it's a GitHub Actions workflow file, you can modify it to add any additional steps you like.

Take a look at [the Hugo docs](https://docs.microsoft.com/azure/static-web-apps/publish-hugo?WT.mc_id=staticwebapps-github-aapowell) which shows the best place to place it, and then how to configure the Action to just look at the pre-generated output.

**Comment by anganti** [comment]
Checkout #17

**Comment by ItalyPaleAle** [comment]
Thanks both, that makes sense and I think it will work, so I'll try again later. I don't think I'm the only person with projects with "special requirements" (or even just using a specific version of Hugo: seems that Oryx always uses the latest which isn't always ideal), so might be a nice thing to write in the docs too 😉
