### ISSUE TITLE
Static Web App's name can be same for two different Static Web Apps across resource groups and subscriptions 

### ISSUE THREAD

**Issue by AshirwadSatapathi** [Azure/static-web-apps#317]
Static web apps can have the same name across resource group and subscription. The only restriction being there in the resource group i.e. Two azure static web apps resources present inside one resource group cannot have the same name. This is quite unique. I'm not sure if this is a feature or what but it's quite different from the azure web apps validation check where we are required to have unique web app name.

![28](https://user-images.githubusercontent.com/23069370/110775630-22bcec80-8285-11eb-9630-a6def4cf6c21.png)

**Comment by mkarmark** [comment]
Yes, this passes our checks because the site is uniquely identifiable since it belongs to different resource groups. The difference between our service and web apps is that web apps uses the sitename to generate the default hostname for the website, so requires that every sitename be unique in order to generate unique hostnames. On the other hand, our default hostname is independent of the sitename since it follows the <adjective>-<noun>-<hex string>.azurestaticapps.net format. Is it a problem to you specifically that you're allowed to create apps of the same name in different resource groups?

**Comment by AshirwadSatapathi** [comment]
Hey @mkarmark, Thanks for updating me regarding it. I was curious to know if you had any plans of having unique names for the static web apps when it goes to GA. If the validation check is modified to have globally unique names for all the static web apps in the GA then it can be a reason of concerns for the existing static web apps which share the common name. I wasn't sure if it was a bug or functionality so created an issue here.

**Comment by miwebst** [comment]
Hi @AshirwadSatapathi, there are no plans to utilize the resource name as the hostname. Creating a generated hostname was done purposefully and is not a bug. There are many resources in Azure that also follow this pattern. It is different from Web Apps so good to call out :)

**Comment by AshirwadSatapathi** [comment]
Thanks @miwebst for the update. It was really helpful.
