### ISSUE TITLE
Detect Angular app and build with ng build --prod

### ISSUE THREAD

**Issue by mahmoudajawad** [Azure/static-web-apps#33]
Referring to the issue I had with an Angular deployment (#31) where it was built using `npm run build` and resulted in the app attempting to connect to local websocket, rather than published websocket and reloading page after some failed attempts, I would like to suggest SWA service recognise Angular projects and build them with `ng build --prod` by default to avoid getting any user of SWA service to failing to update `package.json` or NPM scripts to get the same behaviour.

**Comment by manekinekko** [comment]
Hi @mahmoudajawad thanks for opening this issue.

The default configuration that the Angular CLI generates when scaffolding a project with an `npm run build` script that executes a dev build of your app, ie`ng build`. 

Please note that the `--prod` is a shorthand for "--configuration=production". When true, it sets the build configuration to the `production` target (in the angular.json).

A lot of Angular projects can have many different target builds, not only `production`. Given this assumption, SWA can't explicitly run the `ng build --prod` since the developer may want to run a build against a different target/configuration using SWA.

This is why, SWA only executes the `npm run build` script (or [`npm run build:azure`](https://bit.ly/3ef2l4C)). The developer may then need to update their package.json in order to execute the desired target/configuration.

For more advanced scenarios, you can provide SWA with a custom build command (for both the app and the api) by using the [`app_build_command`](https://bit.ly/3ef2l4C) (and [`api_build_command`](https://bit.ly/3ef2l4C)). Here is an example from a real world app:

https://github.com/manekinekko/catsify/blob/668b2c32411294713b78402da8ed96809ecfc36f/.github/workflows/azure-static-web-apps-witty-flower-06756bd10.yml#L49-L50

**Comment by mahmoudajawad** [comment]
@manekinekMA, amazing! Having the option for custom build command is even better. I overlooked this one. Thanks for explaining it.

**Comment by manekinekko** [comment]
You are welcome @mahmoudajawad

**Comment by brentarias** [comment]
The [documentation ](https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions)makes the following clarification:
> For example, to configure a production build for an Angular application create an npm script named `build-prod` to run `ng build --prod` and enter `npm run build-prod` as the custom command. 

Why is it necessary or relevant to "create an npm script", as stated above, when we can instead simply enter the custom command directly?
