### ISSUE TITLE
Satatic IP address in a static web site

### ISSUE THREAD

**Issue by DFMERA** [Azure/static-web-apps#332]
How can I assign a static ip to a static website? and what are the security and scaling implications of doing this?
Is there any reference documentation that I can use?

Thank you.

**Comment by anthonychu** [comment]
Static Web Apps is a global service so there’s no way to provide a static IP.

**Comment by miwebst** [comment]
Closing this as this is not something we provide. There are some networking security features that are coming soon so you can use those to secure access to your site. If you are trying to secure your network to only allow access to static web apps (rather than the whole internet) then you need a firewall that is capable of supporting fqdn based filtering.
