### ISSUE TITLE
Allow skipping API build

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#343]
Add support for skipping API build (like how we added `skip_app_build`) and allow customer to specify the language for the function app (use an allow list, will eventually need to include language version too).

**Comment by paule96** [comment]
I'm not sure if I should open a new issue for this or write a comment here. So I start with writing a comment here.
Because of this issue, I did reverse engineered the calls that the docker container does in the pipeline. You can find my script [here](https://github.com/codez-one/CZ.Azure.FileExchange/blob/main/build/deploy.ps1).
It's definitely not complete but show what I think most of the enterprise customers want before to work with this kind of technology. A splitting between build and deployment. This script basically just accepts two file paths to the publish output of the app, and just upload it. (see the [readme](https://github.com/codez-one/CZ.Azure.FileExchange))
This script works for me, but it has its issues, here a brief list:
 - there is no force upload. if you want a force upload change a file
 - it does not support right now branch environments (maybe I have time to implement it)
 - it's without warranty 🤷‍♀️

I use this regularly and will maybe replace the current GitHub action / workflow with-it.
Maybe that is just an old and not wanted mindset anymore, but I still have many projects that require the splitting of build and deployment in two different tasks. (Because they are time in depended on and there is usually more than one stage.
So, I hope we can make this possible to do this.

A nice side effect of this is: my deployment times even from my local laptop with bad internet speeds are relatively fast. (Just 2mins or so) With the before used docker container I need around half an hour because he must always download dotnet 6 and all my NuGet packages i use.

So hope this helps a bit more to make this service to be even better. After all I think the service is a really good service and I will try I definitely more often in the feature.

**Comment by svrooij** [comment]
This is related to https://github.com/Azure/static-web-apps/issues/493 and and https://github.com/microsoft/Oryx/issues/1172

We want to deploy this static web app, where the api part has a dependency to a private nuget repository. At the moment there is no way (or not documented) on how get it deployed with that package in the source. I wish not to add the package to nuget.org since it's a private package in a private nuget feed.

We are perfectly able to build the app our self in Azure DevOps, but it won't deploy.

**Comment by anthonychu** [comment]
@Reshmi-Sriram might be able to provide an update on this feature and when it might land in GitHub Actions and Azure Pipelines task.

**Comment by Reshmi-Sriram** [comment]
Hi All,
The code fix for `skip_api_build` flag is complete and we expect it to roll out as a part of GitHub Actions and Azure Pipelines tasks by another 3 weeks! 🎉
CC// @pvbchak

**Comment by Reshmi-Sriram** [comment]
> Hi All, The code fix for `skip_api_build` flag is complete and we expect it to roll out as a part of GitHub Actions and Azure Pipelines tasks by another 3 weeks! 🎉 CC// @pvbchak

**UPDATE**: `skip_api_build` should now be enabled in GitHub Actions!🎉🎉
In order to use it, we need to set `skip_api_build: true` in the GitHub workflow yaml and specify the [ApiRuntime version ](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#selecting-the-api-language-runtime-version) in the `staticwebapp.config.json` file in source repository.

Azure DevOps changes are being merged meanwhile and can be tracked in the following [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15996)

**Comment by svrooij** [comment]
This https://github.com/microsoft/azure-pipelines-tasks/pull/15996 seems to be have merged. That means this issue can be closed as well?

**Comment by collinbarrett** [comment]
When using `skip_api_build`, how do we specify where the pre-built api artifacts live so that `Azure/static-web-apps-deploy` knows where to get the function code artifacts from? The docs for `api_location` specify:

> Directory location of the Azure Functions _**source code**_
(note, "source code", not pre-built artifacts)

Should there be a parameter such as `api_output_location`, `api_artifacts_location`, or similar? I tried tracing down how the client works, but it appears it's not open source yet.

**Comment by anthonychu** [comment]
@collinbarrett Thanks for the suggestion. I've submitted changes to the docs that should be live soon.

**Comment by thomasgauvin** [comment]
The doc changes have been merged, closing this issue
