### ISSUE TITLE
Azure portal app: "Login with GitHub" button not working

### ISSUE THREAD

**Issue by stephtr** [Azure/static-web-apps#43]
I'm not sure whether this is the right place for this issue, but if I use the [Azure Portal app](https://portal.azure.com/App/Download) to create a new Static Web App, the "Login with GitHub" button isn't working.

**Comment by ricksterhd123** [comment]
same

**Comment by ehamai** [comment]
Hi @stephtr, can you give a little more detail as to what you mean by "login with GitHub" isn't working?  Is there any error or does the login pop-up even show?  Also if you can provide a sessionId of a repro then maybe we can see something on our end.

1. Open your browser dev tools (Usually F12)
2. Go to your console and one of the first few lines should be "sessionId"

**Comment by ricksterhd123** [comment]
I might have to disregard my comment because I somehow misread the issue title. 
I had this problem with the azure portal login using firefox on Windows 10. (portal.azure.com)
Anway I guess something went wrong with github OAuth and could also have something to do with my github account using the same email as my azure account.

I hope these images provide more context even though the issues might not be the same:
![image](https://user-images.githubusercontent.com/2502753/86623518-a5383280-bfb9-11ea-8b34-b58b63192786.png)
![image](https://user-images.githubusercontent.com/2502753/86623536-aa957d00-bfb9-11ea-8be8-790db8af44c5.png)
![image](https://user-images.githubusercontent.com/2502753/86623744-f811ea00-bfb9-11ea-80af-1280047d2c80.png)

**Comment by stephtr** [comment]
> Hi @stephtr, can you give a little more detail as to what you mean by "login with GitHub" isn't working? Is there any error or does the login pop-up even show? Also if you can provide a sessionId of a repro then maybe we can see something on our end.
> 
> 1. Open your browser dev tools (Usually F12)
> 2. Go to your console and one of the first few lines should be "sessionId"

I'm talking about [this Azure Portal app](https://portal.azure.com/App/Download). Clicking the button has no effect, there's no popup opening; in the developer console I got the following error (Session: d431d913b966479ca3b40c64269686c5):

![image](https://user-images.githubusercontent.com/5764184/86654209-11c92680-bfe6-11ea-9eee-513d253de269.png)

Apparently `MsPortalImpl/Commands/Commands.OAuthCommand` is relying on `window.open` for opening the login window, which however doesn't work for electron apps (like the Azure Portal app).
