### ISSUE TITLE
HUGO site builds incorrectly

### ISSUE THREAD

**Issue by verbeeckorama** [Azure/static-web-apps#431]
Hi, 

I have a HUGO site which runs locally without issues. 
![image](https://user-images.githubusercontent.com/84269988/119255761-b54f0580-bbbd-11eb-9e6a-6f2683c12e25.png)

However when I create a static web app, with default settings of it, the public website renders improperly. There are two issues:
1. the CSS clearly does not load. If I run inspect in the browser it says: Mixed Content: The page at 'https://thankful-cliff-0d2a87903.azurestaticapps.net/' was loaded over HTTPS, but requested an insecure stylesheet 'http://example.org/css/print.css'. This request has been blocked; the content must be served over HTTPS.
2. when I click on a article, it tries to load it at: http://example.org/artikel3/. 

I'm guessing it also tries to load the CSS file at http://example.org...

My repo: https://github.com/verbeeckorama/my-blog
Actions workflow: https://github.com/verbeeckorama/my-blog/blob/master/.github/workflows/azure-static-web-apps-thankful-cliff-0d2a87903.yml 
Public URL static web app: https://thankful-cliff-0d2a87903.azurestaticapps.net/ 

It might be useful to know that my theme was added as a submodule. 

Thanks for your advice.
Hans

**Comment by anthonychu** [comment]
`http://example.org/` comes from [here](https://github.com/verbeeckorama/my-blog/blob/5084897a7e0f3f001f1fcd12a369a5d22cb3e558/config.toml#L1). It appears your theme appends it to the CSS paths. Update `baseUrl` to `/` and it should work fine.

The reason it's working for you locally is because `hugo serve` sets `baseUrl` to `http://localhost:1313/`. If you just run `hugo` to compile the site, you'll see that the generated `public/index.html` contains references to `example.org`.

**Comment by verbeeckorama** [comment]
OMG. I feel stupid now. It is literally one of the first things I should have changed. Thanks so much for your help!

**Comment by Reshmi-Sriram** [comment]
Closing as resolved
