### ISSUE TITLE
ng build is failing with error TS2307

### ISSUE THREAD

**Issue by KP1980** [Azure/static-web-apps#449]
AzureStaticWebApp step is failing while building angular app with following error even though module path exists in parent directory:

ERROR in src/app/app.module.ts:8:41 - error TS2307: Cannot find module '../interceptor/browserstate.interceptor'.

8 import { BrowserStateInterceptor } from '../interceptor/browserstate.interceptor';

**Comment by anthonychu** [comment]
You might need to provide more information because it’s hard to debug with just this error message. But can you check the casing of the filename of the module you’re importing? The build runs on Linux so filenames are case sensitive. For instance if the file is actually named `browserState.interceptor.ts` (capital `S`), your import also needs to have a capital `S`.

**Comment by KP1980** [comment]
@anthonychu yes, you are right. It was a case issue. The folder name was starting with upper case "Interceptor" and it was starting with lower case in the import statement as you see in the error message. The issue is resolved after changing the case to match the folder name and the import statement.
Thank you!

**Comment by Reshmi-Sriram** [comment]
Marking as resolved
