### ISSUE TITLE
My staticwebapps.config.json file is downloadable from the browser.

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/static-web-apps#456]
I came to realize that maybe the SWA wasn't picking up my staticwebapps.config.json file, so on a whim I tried to access it via the address bar in the browser and it came down.
Went for gold and tried local.settings.json and that came down, too.
Have I misconfigured my static web app? 
Feels pretty horrible that such a thing could happen. 
(Creating this issue is making me also realize I don't have a .gitignore)

**Comment by irwinwilliams** [comment]
Oh, my spelling was bad, I had staticwebapps as opposed to staticwebapp. Carry on. :)

**Comment by anthonychu** [comment]
Where do you have your function app located in your repo? Usually it’s under /api and its contents like local.settings.json are not accessible because that path is routed to the function app. local.settings.json is also in .gitignore by default. How did you create your function app? I want to see if we can improve that.

@miwebst can we search for this common misspelling during the build and raise a warning?

There’s already an issue filed for the CLI to warn https://github.com/Azure/static-web-apps-cli/issues/216 and will see if VS Code can do the same as well.

**Comment by irwinwilliams** [comment]
So, I currently have it at root, but I had it in an /app folder at one point. My local.settings.json is also at root - I thought it would need to be there since staticwebapp.config.json refers to clientIdSettingName and clientSecretSettingName for my custom auth. 
I made the function app in VSCode using the Azure extension for static web apps.
