### ISSUE TITLE
The ability to restart (stop/start) an azure static web app, specifically the Azure Functions

### ISSUE THREAD

**Issue by TellonUK** [Azure/static-web-apps#522]
We are using Azure Static Web apps and are dynamically loading in database schemas from a configuration per client. If we change the schema, then the azure function needs to restart to load the new schema in, or it will just hang when used. This is a development issue, as the schema wouldn't be changed in production, but our implementers change the schemas frequently when designing a customers solution.

Is there some way (like with web apps) to sent a PowerShell, rest, power automate to restart the service? At the moment as a work around we created an environment configuration and manually update it to force a reboot.

**Comment by anthonychu** [comment]
Related #256 #503

**Comment by abatishchev** [comment]
Hi @Reshmi-Sriram, you've closed the issue as completed but didn't provide any details. Would you please?

**Comment by Reshmi-Sriram** [comment]
Hi @abatishchev,
I closed the issue here since it is being tracked at 2 other places, i.e. #256 and #503. Feel free to continue the discussions there since we already have multiple parallel issues for the same.

In case you feel this issue is not-related, kindly let me know we could reopen this issue.
