### ISSUE TITLE
Logout only logs out from the SWA but not the identity provider

### ISSUE THREAD

**Issue by Skleni** [Azure/static-web-apps#529]
I'm using Auth0 as custom provider. When I'm logging out via `.auth/logout`, I'm redirected to `.auth/logout/complete` and the `StaticWebAppsAuthCookie` is deleted. Then I'm redirected again to `/`.

However, it seems I'm still logged in with Auth0, because when I go to `.auth/login/auth0`, I don't have to enter any credentials and I'm automatically authenticated after some redirects.

Is there any way to make the `.auth/logout` endpoint logout from the identity provider as well (and not just the SWA)?

**Comment by Skleni** [comment]
I found a way to do what I want: When the user logs out from my app, I redirect to Auth0's logout endpoint and pass my SWA's `/.auth/logout` endpoint as callback url: (`https://DOMAIN.eu.auth0.com/v2/logout?client_id=CLIENTID&returnTo=MYSWAURL/.auth/logout`

**Comment by AverageCakeSlice** [comment]
@Skleni I just setup the reverse version of this yesterday, where I call `/.auth/logout` via an async GET request and then redirect to the Auth0 logout endpoint, with the returnTo value set back to the welcome page of my app. I had to configure my Auth0 app with the `https://MY_DOMAIN/.auth/logout/callback` and `https://www.MY_DOMAIN/.auth/logout/callback` url's in the allowed callback URL's list, otherwise I'd get a CORS error.

We should get in touch to share knowledge, it sounds like we're coming up against similar obstacles!

**Comment by Skleni** [comment]
I tried something similar too, but then my app ended up showing a blank page after the redirect to `https://MY_DOMAIN/.auth/logout/callback`.
