### ISSUE TITLE
Failed github actions CI/CD deployment  to azure

### ISSUE THREAD

**Issue by Kiptooe** [Azure/static-web-apps#531]
Error: Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.Could not find tools for building monorepos, no 'lerna.json' or 'lage.config.js' files found.

---End of Oryx build logs---
Oryx could not find a 'build' or 'build:azure' script in the package configuration. Please add one of these commands to your package configuration file (i.e. package.json). Alternatively, you can add the app_build_command to the build/deploy configuration section of your workflow file. For example, app_build_command: 'npm run docs:build'

I'm getting this error , yet what I'm deploying to azure is just a static webapp. Correct me if i'm wrong but I think a static website doesn't need node js ?  I'm new to using azure and github actions,  kindly help

**Comment by anthonychu** [comment]
Looks like [this](https://github.com/Emmanuel-Kip/farmer-sconnect/tree/fcb66a63028c4495e33e97077ce890ccf0b225b6) might be the app you're trying to deploy?

It turns out the problem here is that your app is missing an index.html, so our build system, Oryx, thinks it needs to build the app. If you add an index.html or rename your existing HTML file to index.html, it should work. Sorry for the cryptic error message. @miwebst @arroyc any thoughts on how we can improve this?

You can also add the [`skip_app_build`](https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow#skip-building-front-end-app) option to the GitHub action to skip the build entirely. This will ensure that we bypass the build process altogether. However, we require index.html to exist, so you'll still need to add the file.

**Comment by Emmanuel-Kip** [comment]
Thank you ! 
It worked after renaming the main html file to  index.html

**Comment by Reshmi-Sriram** [comment]
Closing as resolved.
