### ISSUE TITLE
Url rewrite in `navigationFallback` stopped working recently

### ISSUE THREAD

**Issue by jeromelaban** [Azure/static-web-apps#663]
**Describe the bug**

The following Uri https://nuget.info/packages fail to route properly and gives a 404. This breaks a lot of scenarios inside the app as a result.

Here's the configuration : https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/ae50e38c82a042a94c7c61b46aa48607e60e98aa/Uno/NuGetPackageExplorer.Wasm/wwwroot/staticwebapp.config.json#L3

**Expected behavior**
Navigating to a sub-path with `navigationFallback` with rewrite should navigate to the rewritten Url, as it was a few days ago.

**Additional context**

**Comment by miwebst** [comment]
We will take a look, thanks for reporting this!

**Comment by miwebst** [comment]
Can you double check that your GitHub Action logs show this line:

Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.

From what I'm seeing, this site had a navigation fallback configured but since around 12/7 15:00 UTC it has no longer been provided. I also confirmed that this behavior is working with the same swa config file when applied to a test site.

**Comment by jeromelaban** [comment]
Thanks for the investigation, we'll take a look at the logs.

**Comment by jeromelaban** [comment]
Indeed the message is not there, and it's related to a .NET 6 upgrade which changed how some assets (wwwroot) are packaged. This is on our end, now. 

Thanks for the very fast response time!
