### ISSUE TITLE
Adding Custom OIDC provider breaks auth. 

### ISSUE THREAD

**Issue by NivGreenstein** [Azure/static-web-apps#736]
It's a bit weird but I created SWA with AAD Auth. When I've added an OIDC provider (Azure B2C in my case), the app stopped redirecting to the auth providers. Neither `/.auth/login/b2c` nor `/.auth/login/aad`.
It literally redirects to `/.auth/login/aad` but not continuing to AD login page.

my code
```
...
"auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "b2c": {
          "enabled": true,
          "registration": {
            "clientIdSettingName": "<clientId>",
            "clientCredential": {
              "clientSecretSettingName": "<secredId>"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://<b2cName>.b2clogin.com/<b2cName>.onmicrosoft.com/B2C_1_signin/v2.0/.well-known/openid-configuration"
            }
          },
          "login": {
            "nameClaimType": "emails",
            "scopes": ["openid"]
          }
        }
      }
    }
  }

```

**Comment by mkarmark** [comment]
This is likely because some part of the custom auth is misconfigured. If you share your app name/details, I'll be able to give you more info on what the misconfiguration is. As for the current setup that you've shared, /.auth/login/aad is no longer going to result in anything because your configuration suggests that this app  has opted for custom auth (not shared auth) but no aad provider has been configured under identityProviders.
