### ISSUE TITLE
Change Branch from `master` to `main` in Environments

### ISSUE THREAD

**Issue by akzaidi** [Azure/static-web-apps#76]
Hi, I changed my default branch in github from `master` to `main`. Is it possible to update my environments to use `main` as the new build branch? I don't see an easy way of editing this on Azure.

**Comment by anganti** [comment]
Just came out for you in time, the az cli support. 

You could use az cli to disconnect and reconnect 

https://docs.microsoft.com/en-us/cli/azure/staticwebapp?view=azure-cli-latest

Let us know if this helps.

**Comment by akzaidi** [comment]
Thanks! I don't see an update parameter for `environment`:

```bash
(azureml) ➜  ~ az staticwebapp environment -h

Group
    az staticwebapp environment : Manage environment of the static app.
        Command group 'staticwebapp' is in preview. It may be changed/removed in a future
        release.
Commands:
    functions : Show information about functions.
    list      : List all environment of the static app including production.
    show      : Show information about the production environment or the specified environment.

For more specific examples, use: az find "az staticwebapp environment"

Please let us know how we are doing: https://aka.ms/azureclihats
```

**Comment by akzaidi** [comment]
Ah I guess I can do a `disconnect` and then a `reconnect`?

**Comment by akzaidi** [comment]
My app directory is `docs`. I don't see an argument for `--app-artifact-location` when I do reconnect, and it looks like reconnect defaulted to `.` rather than what I had originally. Is there a way I can specify the location of the app when I reconnect?

**Comment by anganti** [comment]
@ElleTojaroon could you please help add the parameter. 

@akzaidi to mitigate can you update the workflow file. Does that work for now?

**Comment by akzaidi** [comment]
Ahh it appears after reconnecting my github actions workflow was updated and it modified the app directory to the default value of ".". I updated my workflow yaml and all is good now.

**Comment by kjkent** [comment]
Hey there, sorry to comment on this years-closed issue, but I'm having a similar issue with a new SWA. I can't seem to set any named branch staging environments, and then I realised that the production_branch setting wasn't being applied, and that in-fact the production branch itself (aptly named 'production') was being ignored by Azure SWA.

I tried the commands above but it seems there's been some changes, as `disconnect`/`reconnect` returns the following:
```
Static Web App <app name> already exists in resource group <resource group>
// ... Below this, a page of JSON regarding the various metrics of the SKU
```
It looks like I'll re-provision the SWA to see if that solves things. I'll see if disabling commit signing (somewhat reluctantly... relevant issue: https://github.com/Azure/static-web-apps/issues/241#issue-766829810) temporarily, so that Azure can access the repo rather than relying on my YAML.

If you think this is worth a new issue, let me know and I'll make one!
