### ISSUE TITLE
Feature to create a staging (preview) environment from Azure DevOps

### ISSUE THREAD

**Issue by kshingaims** [Azure/static-web-apps#781]
I refer to [the following comment](https://github.com/Azure/static-web-apps/issues/5#issuecomment-855309670) in #5 and make this request for an additional feature here as a new Issue.
```
Closing this issue. Please create new issues for help or feature requests.
```

Currently, Static Web Apps can only create a staging (Preview) environment through GitHub Actions Pull Requests.
Would you consider the feature to create this staging environment from Azure DevOps?

We hope you will consider this request, as a similar request was made at [#5](https://github.com/Azure/static-web-apps/issues/5#issuecomment-877613954) in July 2021 and the same request is growing in our local area.

**Comment by Reshmi-Sriram** [comment]
Related https://github.com/Azure/static-web-apps/issues/604

Hi @kshingaims!
We have already started working on this ask, as monitored in [this thread](#604).
The [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15981) for the same has been merged and will be released shortly. 
We'll close this issue so that it could be tracked on a single one.
Hope this answers! :)
