### ISSUE TITLE
The number of files in the app content folder exceeds the limit of 15000

### ISSUE THREAD

**Issue by MaximRouiller** [Azure/static-web-apps#782]
```text
---End of Oryx build logs---
Finished building app with Oryx
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: BadRequest
Reason: The number of files in the app content folder exceeds the limit of 15000.
```

I'm trying to deploy 87,814 files (~2.3GB) and it fails.

1. Creating a site with Gatsby that has more than 15000 files (without a node_modules folder)
2. Deploying it to Azure Static Web Apps

Here's the [GitHub Action YAML file](https://github.com/MaximRouiller/azure-rest-api-code-samples/blob/282ae699f8df2deef0507d05a0d9021b4bd1cf70/.github/workflows/azure-static-web-apps-agreeable-glacier-0049d6b10.yml) that caused the issue.

**Expected behavior**

Successful deployment.

**Screenshots**

<img width="182" alt="public folder on my local machine that gets deployed" src="https://user-images.githubusercontent.com/209384/162215771-d2582e29-e3c9-46a9-9979-99a29989e629.png">

**Additional context**

Probably related to https://github.com/Azure/static-web-apps/issues/139

**Comment by MaximRouiller** [comment]
Duplicate of #520.

**Comment by robersonliou** [comment]
How to resolve the issue?

**Comment by NoPodi** [comment]
After getting completely crazy over this issue I found a workaround in deleting the node_modules folder from the app content folder manually via the DeleteFiles task.

But to enable this step one cannot build and deploy via the AzureStaticWebApp task alone so every step is done manually.
Please take this script with a grain of salt because half of the time I have no idea what the settings are for but this worked for me finally.

`# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: 'node_modules'
    RemoveSourceFolder: true

- script: |
    dir
  displayName: 'dir'

- task: AzureStaticWebApp@0
  inputs:
    output_location: '/dist'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
  env:
    azure_static_web_apps_api_token: $(deployment_token)
`

**Comment by tvytlx** [comment]
Adding `app_build_command: "npm run build"` solved my problem.
```yaml
          app_build_command: "npm run build"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
```
