### ISSUE TITLE
Support for Azure Active Directory groups in role management

### ISSUE THREAD

**Issue by bburgin** [Azure/static-web-apps#81]
In an Azure Static Web App, I would like to be able to associate an Azure Active Directory group to a role in the role management options. This would allow me to provide secure access to a group of people in my tenant.
Example routes.json entry:

```json
{
	"routes": [{
		"route": "/index.html",
		"allowedRoles": [
			"reader"
		]
	}]
}
```

**Comment by 0gust1** [comment]
Yes ! and it could also facilitate user invitation / integration : admin-side : adding users to the app in the Azure UI is cumbersome, and user-side, even if the authentication provider is Azure Active Directory, when accessing the app the first time users get an disturbing confirmation screen. A deeper integration with Azure AD could solve this.

**Comment by holwech** [comment]
This feature would definitely be useful to have. We use Azure static web apps to host our documentation and we want some of the documentation to be public, some to be restricted and some of it to be available company wide (aka Azure AD tenant). Currently the company wide access is not possible as far as I can tell.

**Comment by tcc-sejohnson** [comment]
Seconded, heartily.

**Comment by javier-romera** [comment]
> 
> 
> This feature would definitely be useful to have. We use Azure static web apps to host our documentation and we want some of the documentation to be public, some to be restricted and some of it to be available company wide (aka Azure AD tenant). Currently the company wide access is not possible as far as I can tell.

This is a "must have" functionality for the acceptance in a company environment.

**Comment by anthonychu** [comment]
We’re working on locking down AAD login to only users in your tenant. This should satisfy the company login scenario above and hope to have available in the next couple of months.

We’re also investigating how we can integrate with AAD security groups for role based authorization but still early stages and there’s no ETA at this time.

**Comment by GaryParr** [comment]
Is there an update for this? Custom AAD integration is now baked in and includes the ability to bypass invitations. I can't find any documentation on how to assign roles though when the invitation is bypassed. One would assume it would be some kind of claim mapping, say perhaps from security groups.

**Comment by Sam-Rowe** [comment]
Docs suggest this is now available? 
https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad

> Specifically for Azure Active Directory (AAD) registrations, you have the option of providing a tenant, which allows you to bypass the invitation flow for group management.

But I haven't been able to get it to work :(

Any examples?

**Comment by azbpa** [comment]
I was also struggling with the docs since they are not really detailed and also contradictory in my eyes (description in table vs placeholder in the code).

My key mistake was that I added the values of `AAD_CLIENT_ID` and `AAD_CLIENT_SECRET` directly to the code block of the `staticwebapp.config.json` file (like suggested in the code example). However, if you take the field description from the table it gets clear that you just reference to an *Application Setting* which hold the actual values for `AAD_CLIENT_ID` and `AAD_CLIENT_SECRET`.

So I could make it work for me like this:

```
{
    "routes": [
      {
        "route": "/login",
        "rewrite": "/.auth/login/aad"
      },
      {
        "route": "/logout",
        "redirect": "/.auth/logout"
      },
      {
        "route": "/.auth/login/twitter",
        "statusCode": 404
      },
      {
        "route": "/.auth/login/github",
        "statusCode": 404
      }
    ],
    "responseOverrides": {
      "400": {
        "rewrite": "/404.html"
      },
      "401": {
        "redirect": "/login",
        "statusCode": 302
      },
      "404": {
        "rewrite": "/404.html"
      }
    },
    "auth": {
        "identityProviders": {
            "azureActiveDirectory": {
                "registration": {
                    "openIdIssuer": "https://login.microsoftonline.com/<aad-tenant-id>/v2.0",
                    "clientIdSettingName": "client_id",
                    "clientSecretSettingName": "secret_id"
                }
            }
        }
    }
  }
```

![image](https://user-images.githubusercontent.com/2796467/124112759-ec40f280-da6a-11eb-8790-07cdb6e6e2ee.png)

However, what isn't working for me yet is the suggested outsourcing of the `AAD_CLIENT_SECRET` to a KeyVault like described here: https://docs.microsoft.com/en-us/azure/static-web-apps/key-vault-secrets 

Hope that helps.

**Comment by Sam-Rowe** [comment]
Thank you @azbpa I am closer, I get something in the response to /.auth/me 
```
{
  "clientPrincipal": null
}
```

but not sure the authentication rules are working because my route seems to be ignored if I am not logged in. 
```
        {
            "route": "/index.html",
            "allowedRoles": [
                "authenticated"
            ]
        }
```

I am also not sure how to speicify an aad group membership that should match against the claim.

**Comment by yzapara** [comment]
Does any body faced such error when setting up custom authentification with AAD?

AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

`"auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/278a7a4f-5362-4d92-a791-2ef475eef427",
          "clientIdSettingName": "ClientIdSetting",
          "clientSecretSettingName": "ClientSecretSetting"
        },
        "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      }
    }
  }`

![image](https://user-images.githubusercontent.com/3428505/126980957-6e39c3c6-c1bd-4ddf-84f6-1bd38107a234.png)

**Comment by balbany** [comment]
> Thank you @azbpa I am closer, I get something in the response to /.auth/me
> 
> ```
> {
>   "clientPrincipal": null
> }
> ```
> 
> but not sure the authentication rules are working because my route seems to be ignored if I am not logged in.
> 
> ```
>         {
>             "route": "/index.html",
>             "allowedRoles": [
>                 "authenticated"
>             ]
>         }
> ```
> 
> I am also not sure how to speicify an aad group membership that should match against the claim.

I'm also getting this behaviour (with the clientPrincipal coming back null) when I enable the custom AAD auth option (V1 was what I could get working)... difference is that all my routes are authenticated (I don't want any part of the app to anonymously accessible). So the user _**is**_ authenticated, but the call to `/.auth/me` suggests otherwise.

So, my question now is: does using the custom aad auth provider option mean you lose the benefit of all the nice role management features of SWA? For now, I'm just trying to get an id auth token that I can use to call an APIM instance (secured by OAuth), like I can normally do with a regular App Service instance.
