### ISSUE TITLE
Impossible to set up an apex domain via the portal

### ISSUE THREAD

**Issue by benc-uk** [Azure/static-web-apps#880]
**Describe the bug**

You can't currently create an apex custom domain

If you try via the "Azure DNS" path you are not allowed to add an apex domain, nor can you leave the field blank
<img width="432" alt="image" src="https://user-images.githubusercontent.com/14982936/184341798-e0fb94d2-0bf8-4ed0-8221-be6a4fbf5d58.png">

If you try through the "non Azure DNS" path (which did work in the past) the portal never generates a code for you, so it's impossible to create the TXT record
It's like it's validating before generating

<img width="430" alt="image" src="https://user-images.githubusercontent.com/14982936/184341419-49febc04-51c7-4999-90d7-480842c4e38a.png">

I also don't think the docs here are correct, e.g. this step https://docs.microsoft.com/en-gb/azure/static-web-apps/apex-domain-azure-dns#validate-domain-ownership makes no mention of picking the DNS zone from the drop down

**Expected behavior**
I am able to add an apex domain to a static web app

**Screenshots**
See above

**Comment by vivekjilla** [comment]
Hi @benc-uk, we observed that this custom domain (benco.io) is linked to another static site `agreeable-bay-002789003`, and that's why it's unable to link to this static site.

The error message ("The domain name given was not found") is misleading. We will work on getting that fixed.
Apologies for the confusion and inconvenience caused.

Can you try deleting the old site (`agreeable-bay-002789003`) again and once it succeeds, try adding the custom domain here and see if it works.

Please let us know in case of any issues.

**Comment by benc-uk** [comment]
Ahh ok, that makes sense! I had tried to delete that older instance.
I'm in the middle of having to recreate some of my resources in a new subscription and tenant.

It does seem I'm unable to delete the old SWA instance agreeable-bay-002789003, it's been stuck deleting for around 20 hours now

**Comment by benc-uk** [comment]
Eventually after 3 or 4 more tries and a long wait I managed to nuke it

And managed to move the apex domain to a new SWA instance

Closing. Thank you
