### ISSUE TITLE
Custom DNS: help text refers to non-existent command

### ISSUE THREAD

**Issue by benc-uk** [Azure/static-web-apps#881]
**Describe the bug**

When running `az staticwebapp hostname set` with `--no-wait` the message returned tells you to run `az staticwebapp hostname get` but this command doesn't exist

**To Reproduce**
```bash
❯ az staticwebapp hostname set --name short-link -g apps --hostname test.benco.io --no-wait -m dns-txt-token
To get the TXT validation token, please run 'az staticwebapp hostname get -n short-link -g apps --hostname test.benco.io --query "validationToken"'. It may take a few minutes to generate the validation token.

❯ az staticwebapp hostname get -n short-link -g apps --hostname test.benco.io --query "validationToken"
'get' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

**Expected behavior**

There is some way to add a hostname using the CLI

**Screenshots**

**Device info (if applicable):**
 - OS: Ubuntu (WSL)
 - Browser: NA
 - Version 22.04

**Additional context**

**Comment by vivekjilla** [comment]
Hi @benc-uk , that seems to be a bug in the message. I will work with our team get it fixed.

Meanwhile, can you try with `show` instead of `get`, as per https://docs.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest#az-staticwebapp-hostname-show

`az staticwebapp hostname show -n short-link -g apps --hostname test.benco.io --query "validationToken"`

**Comment by benc-uk** [comment]
Yes show seems to work. Thank you
