### ISSUE TITLE
WebApps staging slots can be linked from the preview environment

### ISSUE THREAD

**Issue by takashiuesaka** [Azure/static-web-apps#960]
**Is your feature request related to a problem? Please describe.**
If I link to the backend production WebApps and then create a swa preview environment, I cannot link the prev env to the WebApps slots created from the production WebApps.

**Describe the solution you'd like**
Even if WebApps already linked from swa exist, it is possible to link to WebApps in a different slot.

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by rupareddy5-21** [comment]
Hi @takashiuesaka, this is not possible as of now, a web app can only be linked to one SWA at a time, you can find this in the [official documentation](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-app-service#:~:text=An%20Azure%20App%20Service%20app%20can%20only%20be%20linked%20to%20a%20single%20static%20web%20app%20at%20a%20time). Please let us know if you need more information. Thanks.

**Comment by takashiuesaka** [comment]
HI @rupareddy5-21, I am proposing a feature request. I am already aware of that limitation, but I am very disappointed that I cannot use the slot feature of WebApps because of that limitation.

**Comment by annikel** [comment]
Hi @takashiuesaka 
**I need to correct: We do indeed allow slots to be linked to staging environments.** 
It might be confusing in the Portal UI right now since it will show a validation error after selecting the Web App - but you can go ahead select the staging slot and hit link. This is solely because the validation currently does not get retriggered after the slot selection. We can work on improving this experience.

**Comment by annikel** [comment]
To be able to have a consistent link from your staging environment to your backend slot make sure to use either [Branch environments](https://learn.microsoft.com/en-us/azure/static-web-apps/branch-environments?tabs=github-actions) or [Named environments](https://learn.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=github-actions)

**Comment by takashiuesaka** [comment]
Hi @annikel ,
Thank you for your reply.
My feature request is to be able to link from production and other pre-production environments in one SWA to production and slot in one WebApps. I don't think this is possible.

**Comment by thomasgauvin** [comment]
@takashiuesaka 

I went ahead and tested the use case of SWA prod env -> Web App prod slot & SWA dev env -> Web App dev slot. It worked for me, as you can see here:

![image](https://user-images.githubusercontent.com/35609369/198301791-7552c68e-bab1-436d-acd7-a0e132bcb4cf.png)

So, to your point @takashiuesaka, this use case is supported, but I did run into a bug which may have deterred you from doing this.

There was indeed a UI bug when attempting to link the Web App dev slot to the SWA dev slot after having previously linked the Web App prod slot to the SWA prod slot. The Portal indicates that it cannot link to the web app (due to it already being linked) but this should not occur when it is already linked to the current SWA.

![image](https://user-images.githubusercontent.com/35609369/198302649-97b3cc8d-5a1c-477e-acf3-02df2d74ed73.png)

Can you validate this @annikel? I think we should classify this as a Portal bug

**Comment by takashiuesaka** [comment]
Hi @thomasgauvin, thank you for verifying this.

Yes, I could not link to the WebApps slot because of the error in Portal you showed above.
I understand that it is a bug in Portal, but then how did you link to the slot from pre-production environment?

Could you please tell me how to do it?

**Comment by thomasgauvin** [comment]
@takashiuesaka While the error does pop up in the UI, you can still choose the App Service slot you wish to link your app environment to. Hope this helps! I have logged this bug with the Portal team and will keep you updated when it is fixed.

![image](https://user-images.githubusercontent.com/35609369/199280150-4209b608-c00f-4a58-9a68-3fa6de4a83b6.png)

**Comment by kurt-mueller-osumc** [comment]
Man, I just ran into this bug last week and it's been two years :(.

**Comment by hawkzey** [comment]
The issues with the UI for this feature are terrible, when i try to link a function app slot to the web app staging environment I just get `An error has occurred`. ....

**Comment by sebastianblesgen** [comment]
Same issue as @hawkzey here
![image](https://github.com/user-attachments/assets/2d61b13f-9c5a-476d-b8dc-55973d438aae)

**Comment by hawkzey** [comment]
It also does allow you to do it with some weird UI flows but it then breaks and doesn't let you remove it, is there a better way of doing this via cli?
